language: cpp

env:
  matrix:
    - BASE=R3.14.12.6 V4= BUSY=1-6-1 SEQ=2.2.5 ASYN=4-32 CALC=3-7 AUTOSAVE=5-9 SSCAN=2-11-1 MOTOR=6-9 AREADETECTOR=3-2
    - BASE=R3.15.5 V4=4.7.0 BUSY=1-6-1 SEQ=2.2.5 ASYN=4-32 CALC=3-7 AUTOSAVE=5-9 SSCAN=2-11-1 MOTOR=6-9 AREADETECTOR=3-2
    - BASE=R3.16.1 V4=4.7.0 BUSY=1-6-1 SEQ=2.2.5 ASYN=4-32 CALC=3-7 AUTOSAVE=5-9 SSCAN=2-11-1 MOTOR=6-10 AREADETECTOR=3-2

dist: trusty
addons:
  apt:
    packages:
      - libreadline6-dev
      - libncurses5-dev
      - perl
      - re2c

cache:
  directories:
    - $HOME/.cache/epics
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853

script:
  - export CI_SCRIPTS="${TRAVIS_BUILD_DIR}/ci-scripts"
  - source "${CI_SCRIPTS}/epics-config.sh"
  - bash "${CI_SCRIPTS}/install-epics-base.sh"
  - if [ ! -z "${V4}" ]; then 
        bash "${CI_SCRIPTS}/install-epics-v4.sh"
    fi
  - bash "${CI_SCRIPTS}/install-epics-modules.sh"
  - if [ ! -z "${AREADETECTOR}" ]; then
        bash "${CI_SCRIPTS}/install-epics-areadetector.sh"
    fi
  - bash "${CI_SCRIPTS}/install-epics-iocs.sh"

  # for projects using the pyepics test IOC and motorsim IOC:
  # - bash "${CI_SCRIPTS}/run-epics-iocs.sh"
  # - pip install pyepics numpy
  # - bash ${CI_SCRIPTS}/run-pyepics-simulator.sh

  - export VERSION_TAG=${BASE}_busy${BUSY}_seq${SEQ}_asyn${ASYN}_calc${CALC}_motor${MOTOR}
  - export FILE_TO_UPLOAD="${TRAVIS_BUILD_DIR}/epics-ci-${TRAVIS_TAG}_${VERSION_TAG}.tar.bz2"
  - tar cfj ${FILE_TO_UPLOAD} ${EPICS_ROOT} 

deploy:
    provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    skip_cleanup: true
    file_glob: true
    file: "${FILE_TO_UPLOAD}"
    on:
      tags: true
