language: cpp

env:
  matrix:
    - BASE_VER=R3.14.12.6 PVA= BUSY_VER=1-6-1 SEQ_VER=2.2.5 ASYN_VER=4-32
      CALC_VER=3-7 AUTOSAVE_VER=5-9 SSCAN_VER=2-11-1 MOTOR_VER=6-9
      AREADETECTOR_VER=3-2 STATIC_BUILD=YES
    - BASE_VER=R3.15.5 PVA=4.7.0 BUSY_VER=1-6-1 SEQ_VER=2.2.5 ASYN_VER=4-32
      CALC_VER=3-7 AUTOSAVE_VER=5-9 SSCAN_VER=2-11-1 MOTOR_VER=6-9
      AREADETECTOR_VER=3-2 STATIC_BUILD=YES
    - BASE_VER=R3.16.1 PVA=4.7.0 BUSY_VER=1-6-1 SEQ_VER=2.2.5 ASYN_VER=4-32
      CALC_VER=3-7 AUTOSAVE_VER=5-9 SSCAN_VER=2-11-1 MOTOR_VER=6-10
      AREADETECTOR_VER=3-2 STATIC_BUILD=YES
    - BASE_VER=R7.0.1.1 PVA= BUSY_VER=1-7 SEQ_VER=2.2.5 ASYN_VER=4-33
      CALC_VER=3-7 AUTOSAVE_VER=5-9 SSCAN_VER=2-11-1 MOTOR_VER=6-10
      AREADETECTOR_VER=3-2 STATIC_BUILD=YES

dist: trusty
addons:
  apt:
    packages:
      - perl
      - re2c
      - autoconf  # pvaPy
      - libboost-all-dev  # pvaPy
      - procserv  # optional, used by ci-scripts/run-epics-iocs-on-procserv.sh

cache:
  directories:
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853

script:
  - export CI_SCRIPTS="${TRAVIS_BUILD_DIR}/ci-scripts"
  - source "${CI_SCRIPTS}/epics-config.sh"
  - bash "${CI_SCRIPTS}/install-epics-base.sh"
  - if [[ ! -z "${PVA}" ]]; then 
        bash "${CI_SCRIPTS}/install-epics-v4.sh";
    fi
  - bash "${CI_SCRIPTS}/install-epics-modules.sh"
  - if [[ ! -z "${AREADETECTOR_VER}" ]]; then
        bash "${CI_SCRIPTS}/install-epics-areadetector.sh";
    fi
  - bash "${CI_SCRIPTS}/install-epics-iocs.sh"

  # for projects using the pyepics test IOC and motorsim IOC:
  # - bash "${CI_SCRIPTS}/run-epics-iocs-on-procserv.sh"
  # - pip install pyepics numpy
  # - bash ${CI_SCRIPTS}/run-pyepics-simulator.sh procserv

  - ldd ~/epics/${BASE_VER}/base/bin/linux-x86_64/caget
  - ldd ~/epics/${BASE_VER}/iocs/pyepics-test-ioc/bin/linux-x86_64/testioc
  - ldd ~/epics/${BASE_VER}/iocs/motorsim/bin/linux-x86_64/mtrSim
  - ldd ~/epics/${BASE_VER}/support/areadetector/${AREADETECTOR_VER}/ADSimDetector/iocs/simDetectorIOC/bin/linux-x86_64/simDetectorApp

  - export VERSION_TAG=${BASE_VER}_pva${PVA}_areadetector${AREADETECTOR_VER}_motor${MOTOR_VER}
  - |
    cat <<EOF > ${EPICS_ROOT}/../versions.sh
    #!/bin/bash
    export BASE_VER=${BASE_VER}
    export PVA=${PVA}
    export BUSY_VER=${BUSY_VER}
    export SEQ_VER=${SEQ_VER}
    export ASYN_VER=${ASYN_VER}
    export CALC_VER=${CALC_VER}
    export AUTOSAVE_VER=${AUTOSAVE_VER}
    export SSCAN_VER=${SSCAN_VER}
    export MOTOR_VER=${MOTOR_VER}
    export AREADETECTOR_VER=${AREADETECTOR_VER}
    export EOT_STATIC_BUILD=${STATIC_BUILD}
    export EOT_VERSION_TAG=${VERSION_TAG}
    EOF

  - export FILE_TO_UPLOAD="${TRAVIS_BUILD_DIR}/epics-ci-${TRAVIS_TAG}_${VERSION_TAG}.tar.bz2"
  - tar cfj ${FILE_TO_UPLOAD} ${EPICS_ROOT} ${EPICS_ROOT}/../versions.sh

deploy:
    provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    skip_cleanup: true
    file_glob: true
    file: "${FILE_TO_UPLOAD}"
    on:
      tags: true
